In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6852, 8830, 4397, 223],
 [6852, 8830, 4397, 5633],
 [6852, 6184, 4397, 268],
 [6634, 4084, 4114, 7848, 9693],
 [6634, 4084, 4114, 7848, 5805],
 [3262, 6852, 4266, 4397, 6413],
 [4360, 744, 9137, 7848]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6852 8830 4397  223]
 [   0    0    0    0 6852 8830 4397 5633]
 [   0    0    0    0 6852 6184 4397  268]
 [   0    0    0 6634 4084 4114 7848 9693]
 [   0    0    0 6634 4084 4114 7848 5805]
 [   0    0    0 3262 6852 4266 4397 6413]
 [   0    0    0    0 4360  744 9137 7848]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 278ms/step


array([[[ 0.02295396,  0.02712582,  0.01331278, -0.02066182,
         -0.01108013, -0.02231259, -0.0337631 , -0.01751863,
         -0.01592411, -0.00629408],
        [ 0.02295396,  0.02712582,  0.01331278, -0.02066182,
         -0.01108013, -0.02231259, -0.0337631 , -0.01751863,
         -0.01592411, -0.00629408],
        [ 0.02295396,  0.02712582,  0.01331278, -0.02066182,
         -0.01108013, -0.02231259, -0.0337631 , -0.01751863,
         -0.01592411, -0.00629408],
        [ 0.02295396,  0.02712582,  0.01331278, -0.02066182,
         -0.01108013, -0.02231259, -0.0337631 , -0.01751863,
         -0.01592411, -0.00629408],
        [-0.0255407 , -0.03197316,  0.03260393,  0.04106588,
         -0.00679924,  0.02089674, -0.03987218,  0.02602394,
          0.03470595, -0.01413709],
        [ 0.03483485,  0.01636663, -0.04964154,  0.04229802,
          0.04282046, -0.01868717,  0.00855643,  0.03638547,
         -0.01996744, -0.0426821 ],
        [-0.01178109,  0.03357725,  0.03419809, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 6852, 8830, 4397,  223])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 52ms/step


array([[ 0.02295396,  0.02712582,  0.01331278, -0.02066182, -0.01108013,
        -0.02231259, -0.0337631 , -0.01751863, -0.01592411, -0.00629408],
       [ 0.02295396,  0.02712582,  0.01331278, -0.02066182, -0.01108013,
        -0.02231259, -0.0337631 , -0.01751863, -0.01592411, -0.00629408],
       [ 0.02295396,  0.02712582,  0.01331278, -0.02066182, -0.01108013,
        -0.02231259, -0.0337631 , -0.01751863, -0.01592411, -0.00629408],
       [ 0.02295396,  0.02712582,  0.01331278, -0.02066182, -0.01108013,
        -0.02231259, -0.0337631 , -0.01751863, -0.01592411, -0.00629408],
       [-0.0255407 , -0.03197316,  0.03260393,  0.04106588, -0.00679924,
         0.02089674, -0.03987218,  0.02602394,  0.03470595, -0.01413709],
       [ 0.03483485,  0.01636663, -0.04964154,  0.04229802,  0.04282046,
        -0.01868717,  0.00855643,  0.03638547, -0.01996744, -0.0426821 ],
       [-0.01178109,  0.03357725,  0.03419809, -0.00410663,  0.02526486,
         0.00273573,  0.03849793,  0.04429236